<?php
$version = 'v1.7.15';
$pagedata = array(
    'v1.7' => array(
       'title_1' => '<div style="color:#ffffff;">- Version 1.7*</div>',
        'description' => '-Version 1.7-',
        'filename' => 'simple.php'),
      'default' => array(
        'title_1' => 'Simple usage',
        'description' => 'This is a simpliest example',
        'filename' => 'simple.php'),   
      'simple_grouping' => array(
        'title_1' => 'Field Grouping <span class="new">NEW</span>',
        'description' => 'simple column grouping,summation of a column value, inline editing',
        'filename' => 'simple_grouping.php'),      
      'relation_grouping' => array(
            'title_1' => 'Relation Field Grouping <span class="new">NEW</span>',
            'description' => 'relation grouping,summation of a column value, inline editing',
            'filename' => 'field_grouping_relation.php'),      
      'simple_translation' => array(
        'title_1' => 'Whole page translation<span class="new">NEW</span>',
        'description' => 'All page words translation',
        'filename' => 'simple_translation.php'),   
      'simple_with_logging' => array(
        'title_1' => 'Simple Table Loggings <span class="new">NEW</span>',
        'description' => 'All actions of a table are logged',
        'filename' => 'simple_with_logging.php'), 
      'logs' => array(
        'title_1' => 'Logs <span class="new">NEW</span>',
        'description' => 'All actions of a table are logged in this table',
        'filename' => 'logs.php'),     
      'video_uploads' => array(
        'title_1' => 'Video Upload <span class="new">NEW</span>',
        'description' => 'Video Uploads',
        'filename' => 'video.php'),  
      'send_email' => array(
        'title_1' => 'Send Email <span class="new">NEW</span>',
        'description' => 'Send Email',
        'filename' => 'sendemail.php'),     
      'edit_buttons' => array(
            'title_1' => 'Edit Buttons Outlay <span class="new">NEW</span>',
            'description' => 'Edit Buttons',
            'filename' => 'edit_buttons.php'),                  
     'edit_modal' => array(
        'title_1' => 'Edit - Modal',
        'description' => 'Edit Through Modal Form',
        'filename' => 'edit_modal.php'), 
     'edit_side' => array(
        'title_1' => 'Edit - Side Panel',
        'description' => 'Edit Form is placed on the side',
        'filename' => 'edit_side.php'),
     'edit_modal_nested' => array(
        'title_1' => 'Edit - Modal (Nested Tab)',
        'description' => 'Edit through a Modal Form with nested tab',
        'filename' => 'edit_modal_nested.php'),
     'edit_side_nested' => array(
        'title_1' => 'Edit - Side Panel (Nested tab)',
        'description' => 'Edit a form with nested tab, placed on the side',
        'filename' => 'edit_side_nested.php'), 
     'inline_editing' => array(
        'title_1' => 'Inline Editing',
        'description' => 'Inline Editing - Single Click on any cell and begin editing',
        'filename' => 'inline_editing.php'),
     'inline_editing_4' => array(
        'title_1' => 'Inline Editing (Enter to Save)',
        'description' => 'Inline Editing with no button to save, Enter to save',
        'filename' => 'inline_editing_4.php'),    
     'inline_editing_1' => array(
        'title_1' => 'Inline Editing (Double Click)',
        'description' => 'Inline Editing - One Column Only(Customer Number) - Double Click ',
        'filename' => 'inline_editing_1.php'),   
     'inline_editing_2' => array(
        'title_1' => 'Inline Editing (Validation)',
        'description' => 'Inline Editing and using the normal validation and also relations',
        'filename' => 'inline_editing_2.php'),  
     'inline_editing_3' => array(
        'title_1' => 'Inline Editing (Parsley Validation)',
        'description' => 'Inline Editing while doing validation using parsely validator',
        'filename' => 'inline_editing_3.php'), 
     'inline_editing_5' => array(
        'title_1' => 'Inline Editing (Multiple Instances)',
        'description' => 'Inline Editing for two xcrud instances',
        'filename' => 'inline_editing_5.php'), 
     'inline_editing_6' => array(
        'title_1' => 'Inline Editing (Nested Tab)',
        'description' => 'Do inline editing to tables inside tabs',
        'filename' => 'inline_editing_6.php'),                         
     'bulk_delete' => array(
        'title_1' => 'Bulk Delete',
        'description' => 'Bulk Delete - Select multiple records and delete. You cannot delete the record with a key : EBGC57SXM-VW47I6AF-401X7DYM',
        'filename' => 'bulk_delete.php'), 
       'parsley_validation' => array(
      'title_1' => 'Parsley Validation',
        'description' => 'Parsley Validation - Do parley validations on the form',
        'filename' => 'parsley.php'), 
     'simple_next_prev' => array(
        'title_1' => 'Form Nav.(Next - Prev)',
        'description' => 'Move Next and Previous in a form',
        'filename' => 'simple_next_prev.php'), 
      'arrange_fields' => array(
        'title_1' => 'Grouping Form Fields',
        'description' => 'Group and Arrange Form Fields',
        'filename' => 'fields_grouping.php'),                                  
      'toast_messages' => array(
        'title_1' => 'Toast Alerts',
        'description' => 'Try to edit, remove the email and save. Toast alert will be displayed. They can be activated or deactivated from config file',
        'filename' => 'toast_alerts.php'),                         
     'tabulator_overview' => array(
        'title_1' => 'Tabulator Overview',
        'description' => 'Tabulator Overview',
        'filename' => 'tabulator_overview.php'),      
     'tabulator_simple' => array(
        'title_1' => 'Tabulator Simple',
        'description' => 'Tabulator, Simple Display with Movable Columns',
        'filename' => 'tabulator_simple.php'),
     'tabulator_formatting' => array(
        'title_1' => 'Tabulator Formatting',
        'description' => 'Tabulator Formatting',
        'filename' => 'tabulator_formatting.php'),
    'tabulator_freeze_row' => array(
        'title_1' => 'Tabulator Freeze Row',
        'description' => 'Tabulator Freeze Row',
        'filename' => 'tabulator_freeze_row.php'),  
     'tabulator_column_calculations' => array(
        'title_1' => 'Tabulator Column Calculations',
        'description' => 'Tabulator Column Calculations',
        'filename' => 'tabulator_column_calculations.php'),   
    'tabulator_level1_grouping' => array(
        'title_1' => 'Tabulator Grouping (level 1)',
        'description' => 'Tabulator Group by one field',
        'filename' => 'tabulator_grouping_level1.php'), 
    'tabulator_relations' => array(
        'title_1' => 'Tabulator Relations',
        'description' => 'Tabulator Relations',
        'filename' => 'tabulator_relations.php'),     
    'tabulator_level2_grouping' => array(
        'title_1' => 'Tabulator Grouping (level 2)',
        'description' => 'Tabulator Group by two fields',
        'filename' => 'tabulator_grouping_level2.php'),     
    'v1.6' => array(
        'title_1' => '<div style="color:#ffffff;">---- Version 1.6* ----</div>',
        'description' => '----Version 1.6*----',
        'filename' => '---'),         
    'base_field_types' => array(
        'title_1' => 'Base field types',
        'description' => 'Basic field types support. Xcrud tries to define type automatically from database, or you can set it manualy',
        'filename' => 'base_field_types.php'),
    'uploads' => array(
        'title_1' => 'Uploads demo',
        'description' => 'Demo of file and images uploading',
        'filename' => 'uploads.php'),
    'cke_and_custom' => array(
        'title_1' => 'CKEditor and custom',
        'description' => 'CKEditor loading and custom field types',
        'filename' => 'cke_and_custom.php'),
    'validation' => array(
        'title_1' => 'Simple validation',
        'description' => 'This is only client-side simple javascript validation. You can use default presets or create your own RegExp',
        'filename' => 'validation.php'),
    'relations' => array(
        'title_1' => 'Simple relation',
        'description' => 'You can get options list from other table',
        'filename' => 'relations.php'),
    'multi_instance' => array(
        'title_1' => 'Multiple instances',
        'description' => 'Unlimited number of instances per page',
        'filename' => 'multi_instance.php'),
    'comments_like' => array(
        'title_1' => 'Coments like template',
        'description' => 'This trick allows you use add and grid view per one page',
        'filename' => 'comments_like.php'),
    'all_disabled' => array(
        'title_1' => 'All disabled',
        'description' => 'Lets disable some features',
        'filename' => 'all_disabled.php'),
    'nested' => array(
        'title_1' => 'Nested tables',
        'description' => 'Example of table nesting',
        'filename' => 'nested.php'),
    'nested_in_tabs' => array(
        'title_1' => 'Nested tables in tabs',
        'description' => 'Example of table nesting in tabs implementation',
        'filename' => 'nested_in_tabs.php'),
    'dependent_dropdowns' => array(
        'title_1' => 'Dependent dropdowns',
        'description' => '',
        'filename' => 'dependent_dropdowns.php'),
    'date_range' => array(
        'title_1' => 'Date range',
        'description' => '',
        'filename' => 'date_range.php'),
    'gallery' => array(
        'title_1' => 'Gallery',
        'description' => '',
        'filename' => 'gallery.php'),
    'million' => array(
        'title_1' => 'One million rows',
        'description' => 'Demo with very large tables. Don\'t forget, that in large tables your columns must be indexed to give you maximum speed',
        'filename' => 'million.php'),
    'buttons_move' => array(
        'title_1' => 'Buttons panel',
        'description' => 'Move bottons panel in left/right side or disable it. <strong>Note:</strong> This will not disable button actions',
        'filename' => 'buttons_move.php'),
    'join' => array(
        'title_1' => 'Join other table',
        'description' => 'Allows you to join other tables. Only INNER JOIN supported. Keys in all joined tables must exist and be unique',
        'filename' => 'join.php'),
    'subselect' => array(
        'title_1' => 'Subselect and sum row',
        'description' => 'Subselect() will create a new column with some value from other (or current) table. You can use any columns from current tables as parameters. Subselect will be called for each row',
        'filename' => 'subselect_and_sum.php'),
    'columns_and_fields' => array(
        'title_1' => 'Columns and fields',
        'description' => 'Select only needed columns and fields',
        'filename' => 'columns_and_fields.php'),
    'tabs' => array(
        'title_1' => 'Tabs',
        'description' => 'Tabs can be created in details view with fields() method',
        'filename' => 'tabs.php'),
    'width_and_cut' => array(
        'title_1' => 'Column width/cut',
        'description' => 'You can set width for any column(s) in a grid.',
        'filename' => 'width_and_cut.php'),
    'modal_and_buttons' => array(
        'title_1' => 'Modal and buttons',
        'description' => 'Modal() can show full value of separate cell in modal window. Additional buttons can be added in buttons columns. Button() method supports {field_tags}',
        'filename' => 'modal_and_buttons.php'),
    'labels_classes' => array(
        'title_1' => 'Labels and classes',
        'description' => 'Label() method will change all field names in all screens, column_name() - only grid headers.',
        'filename' => 'labels_and_classes.php'),
    'name_and_tooltips' => array(
        'title_1' => 'Tooltips',
        'description' => 'Any tooltips. Table name.',
        'filename' => 'name_and_tooltips.php'),
    'highlights' => array(
        'title_1' => 'Highlights',
        'description' => 'Highlight separate cells and full rows.',
        'filename' => 'highlights.php'),
    'grid_tricks' => array(
        'title_1' => 'Grid tricks',
        'description' => 'Clickable column - very simple',
        'filename' => 'grid_tricks.php'),
    'js_tricks' => array(
        'title_1' => 'JS tricks',
        'description' => 'Some js functions example',
        'filename' => 'js_tricks.php'),
    'action' => array(
        'title_1' => 'Ajax action',
        'description' => 'You can extend your buttons and links to be usable with xcrud\'s ajax interface. Your buttons can call functins, defined in your externall file. You must create action callback and add attributes to target element (button or something else)',
        'filename' => 'action.php'),
    'fk_relation' => array(
        'title_1' => 'Many-to-many relations',
        'description' => 'Many-to-many (FK) relations can be displayed as simple multiselect fields. This method changes only fk table.',
        'filename' => 'fk_relation.php'),
    'ordering' => array(
        'title_1' => 'Ordering example',
        'description' => 'This example uses create_action() callback for building this feature',
        'filename' => 'ordering.php'),
    'select2' => array(
        'title_1' => 'Select2 usage',
        'description' => 'How to connect Xcrud and Select2, reinitialization after ajax request',
        'filename' => 'select2.php'),
    );
?>